[package]
name = "btrblocks-rs"
version = "0.1.0"
edition = "2021"
authors = ["Emre Bicer <oebicer@gmail.com>"]

[lib]
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"

[dev-dependencies]
rand = "0.8.5"
num = "0.4"

[build-dependencies]
cxx-build = "1.0"
cmake = "0.1"
git2 = "0.18.2"
